#!/usr/bin/env bash
trap 'rm -f ./mod.7z; exit 0' TERM
./compile &>/dev/null || {
  echo "fail exit"
  exit 1
}
7zz a -mx9 -md64m mod.7z mathbreakers/BepInEx/plugins &>/dev/null
echo mod.7z

while :; do
  sleep 1
done
