<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net35</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="WebSocketSharp" Version="1.0.3-rc11" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>../mathbreakers/BepInEx/core/BepInEx.dll</HintPath>
    </Reference>

    <Reference Include="0Harmony">
      <HintPath>../mathbreakers/BepInEx/core/0Harmony.dll</HintPath>
    </Reference>

    <Reference Include="UnityEngine">
      <HintPath>../mathbreakers/Mathbreakers_Data/Managed/UnityEngine.dll</HintPath>
    </Reference>

    <Reference Include="Assembly-CSharp">
      <HintPath>../mathbreakers/Mathbreakers_Data/Managed/Assembly-CSharp.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
